// 1) PRINTING HELLO WORLD
fun main(){
    println("Hello World!!")

// 2) VAL, VAR, VARIABLES AND DATA TYPES - INTEGER, FLOAT, DOUBLE FLOAT, BOOLEAN, STRING
//    SO VAL IS USED FOR ASSIGNING A PERMANENT VALUE TO A VARIABLE
//    WE DON'T NEED TO EXPLICITLY ASSIGN DATA TYPES TO VARIABLES AS THE KOTLIN COMPILER LIKE PYTHON WHILE COMPILING THE CODEBASE AUTOMATICALLY
//    FINDS OUT THE VALUE AND THE CORRESPONDING DATA TYPE AND ASSIGN IT TO THE VARIABLE
//    SO THE SYNTAX FOR DECLARING A VARIABLE AND ITS DATA TYPE IS var/var X: Int(Data-type) = value
//  3) INTEGER USING VAL
    val x: Int = 5
    println(x)
//  4)  VAR IS USED FOR ASSIGNING A TEMPORARY VALUE TO A VARIABLE
    var y: Int = 7
    y=10
    println(y)
//   5) SO FIRST DATA TYPE WE SAW WAS INTEGER NOW LETS LOOK AT FLOAT
//    IF YOU ARE ASSIGNING A WHOLE NUMBER TO FLOAT ADD F IN THE END
//    FLOAT CAN STORE 32 BIT NUMBERS WHEN IT COMES TO STORING DIGITS ON THE DECIMAL SIDE
    var z: Float = 10f
    println(z);
//    6) - NOW LETS LOOK AT DOUBLE
//    DOUBLE CAN STORE 64 BIT NUMBER WHEN IT COMES TO STORING DIGITS ON THE DECIMAL SIDE
    val a:  Double = 10.123
    println(z)
//    7) - NOW LETS LOOK AT BOOLEAN
    val b: Boolean= true
    println(b)
//    8) NOW LETS LOOK AT STRINGS
    val c: String = "This is a string"
    println(KotlinVersion.CURRENT)
}