
// FUNCTION OVERLOADING
// EXTENSION FUNCTION CAN BE USED FOR SPECIFIC DATA TYPE OBJECTS BUT WHAT IF NOW YOU WANT TO USE ANOTHER DATA TYPE OBJECT??
// LET'S EXPLAIN THIS SITUATION WITH AN EXAMPLE SO IN THE LAST FILE WE DEFINED AN EXTENSION FUNCTION THAT REVERSES THE DATA
// TYPE STRING BUT NOW WHAT IF YOU WANT TO REVERSE AN INTEGER INSTEAD OF STRING FOR THE SAME
// WE TACKLE THIS PROBLEM USING FUNCTION OVERLOADING
// SO IN FUNCTION OVERLOADIG YOU CAN CREATE A SEPERATE FUNCTION
fun main(){
    println("Enter an integer to be reversed: ")
    val input_integer = readln().toIntOrNull()
    if (input_integer != null) {
        val reversed_integer_output = input_integer.reversed_string()
        println("The reversed integer output is: $reversed_integer_output")
    }
}
// LET THE ORIGINAL FUNCTION DEFINED TO REVERSE THE DATA TYPE STRING BE AS IT IS
fun String.reversed_string(): String{
    val final_reversed_string = buildString {
        for(i in this@reversed_string.lastIndex downTo 0){
            append(this@reversed_string[i])
        }
    }
    return final_reversed_string
}
// NOW WE CAN USE THE SAME FUNCTION WHICH WAS EARLIER DEFINED TO REVERSE THE DATA TYPE STRING TO ALSO REVERSE AN INTEGER BY INITIALLY DEFINING THE
// DATA TYPE YOU WANT TO OVERLOAD TO THE FUNCTION AND THEN DECLARING THE SAME OLD FUNCTION THAT WAS USED TO REVERSE A STRING AND ALSO DONT FORGET
// TO DECLARE THE RETURN DATA TYPE OF THE FUNCTION AND THE YOU CAN USE THE 'this' KEYWORD TO REFERENCE THIS INCOMING INTEGER WITH THE SAME FUNCTION
// NAME
// SO IN THIS FUNCTION WE ARE USING THE 'this' KEYWORD TO REFERENCE THE INCOMING INTEGER AND THEN WE ARE CONVERTING THE INTEGER TO A STRING T
// AS THE ORIGINAL FUNCTION ONLY TAKES STRINGS TO REVERSE THEN WE ARE CALLING THE ORIGINAL FUNCTION AND THEN IT RETURNS THE REVERSED INTEGERS AS A
// A STRING AND THEN WE ARE AGAIN CONVERTING THIS STRING TO THE ORIGINAL INTEGER VALUE USING TOINTORNULL AND THEN ALSO HANDLING AN EDGE OF CASE OF
// IT NOT BEING AN INTEGER IT WILL ASSIGNED THE VALUE 0 USING THE ?: OPERATOR S
fun Int.reversed_string(): Int{
    return this@reversed_string.toString().reversed_string().toIntOrNull()?:0
}

// YOU CAN ALSO OVERLOAD A NORMAL FUNCTION JUST LIKE THAT THERES NO DIFFERENCE BETWEEN OVERLOADING A FUNCTION FOR A NORMAL AND EXTENSION FUNCTION
fun normal_reversed_function(input_string_to_be_reversed: String): String{
    val reversed_string = buildString {
        for( i in input_string_to_be_reversed.lastIndex downTo 0){
            append(input_string_to_be_reversed[i])
        }
    }
    return reversed_string
}
fun normal_reversed_function(input_of_integer_to_be_reversed: Int): Int{
    return input_of_integer_to_be_reversed.toString().normal_reversed_function().toIntOrNull()?:0
}

// BUT WHAT YOU CANNOT DO IS TRY TO OVERLOAD THE FUNCTION WITH SAME DATA TYPE OBJECT TO BE CALLED THAT ALSO HAS THE SAME RETURN TYPE AS THE ORIGINAL
// FUNCTION SO IN THIS CASE THE COMPILER WOULDNT KNOW WHICH FUNCTION TO CALL AS THEY BOTH ARE BASICALLY DUPLICATES OF EACH OTHER SO HERE BELOW
// WE CAN SEE THAT THE COMPILER SAYS CONFLICTING OVERLOADING FUNCTION

//fun original_function(input_string: String): Int {
//
//}
//fun original_function(input_string: String): String{
//
//}