fun main() {
//    1) ARITHMETIC OPERATORS - ADDITION - '+'
    var x: Int = 11
    var y: Int = 9
    println(x+y)
//    2) SUBTRACTION - '-'
    println(x-y)
//    3) MULTIPLICATION - '*'
    println(x*y)
//    4) DIVISION - '/'
//    IF YOU NOTICE DIVISION OF INTEGER WILL ONLY RETURN ANOTHER INTEGER AS THE RESU
//    LT
    println(x/y)
//   5) MODULUS - '%'
//    MODULUS PERFORMS DIVISIONS ON THE NUMBERS AND RETURNS THE REMAINDER
    println(x%y)
//    6) X++
//    IT ADDS ONE TO THE VARIABLE AND STORES IT ACCORDINGLY TO THE VARIABLE ITSELF
    x++
    println(x)
//    7) X--
//    IT SUBTRACTS ONE FROM THE VARIABLE AND STORES IT ACCORDINGLY TO THE VARIABLE ITSELF
    x--
    println(x)
//    8) X+=N
//    IT ADDS THE GIVEN NUMBER ON THE RIGHT-SIDE OF THE OPERAND AND TO THE VARIABLE AND SUBSTITUTES AND STORES IT IN THE VARIABLE ACCORDINGLY
    x+=5
    println(x)
//    9) X-=N
//    IT SUBTRACTS THE GIVEN NUMBER ON THE LEFT-SIDE OF THE OPERAND AND TO THE VARIABLE AND SUBSTITUTES AND STORES IT IN THE VARIABLE ACCORDINGLY
    x-=5
    println(x)
//    10) X*=N
//    IT MULTIPLIES THE GIVEN NUMBER ON THE RIGHT-SIDE OF THE OPERAND AND TO THE VARIABLE AND SUBSTITUTES AND STORES IT IN THE VARIABLE ACCORDINGLY
    x*=3
    println(x)
//    11) X/=N
//    IT MULTIPLIES THE GIVEN NUMBER ON THE RIGHT-SIDE OF THE OPERAND AND TO THE VARIABLE AND SUBSTITUTES AND STORES IT IN THE VARIABLE ACCORDINGLY
    x/=11
    println(x)
}
