fun main(){
    val x=10
    val y=11
// LOGICAL OPERATORS USED TO CHAIN ARTHIMETIC OPERATORS AS WELL MULTIPLE CONDITIONS TO RETURN BOOLEAN VALUE WHETHER THE GIVEN CONDITION
//  IS TRUE OR NOT

//    AND OPERATOR - IS DENOTED BY &&
//    AND OPERATOR IS USED TO CHAIN 2 CONDITIONS TO CHECK IF IT SATISFIES ALL THE CONDITIONS
//    IT WORKS BASED ON THE AND TRUTH TABLE
//    IT'S TRUE ONLY IF BOTH CONDITIONS ARE SATISIFIED
    val are_both_even= x%2==0 && y%2==0
    println(are_both_even)

//    OR OPERATOR - IS DENOTED AS ||
//    OR OPERATOR IS USED TO CHAIN 2 OR MORE CONDITIONS TO CHECK IF IT SATISFIES AT LEAST ONE OR MORE CONDITIONS
//    IT'S TRUE IF EITHER OR BOTH OF THE CONDITIONS ARE TRUE
    val is_at_least_one_even= x%2==0 || y%2==0
    println(is_at_least_one_even)

//    AND THESE OPERATIONS WORK BASED ON ORDER WHEN NESTED WITH ONE AND ANOTHER FOR EXAMPLE
    val is_at_least_one_even_and_is_both_sum_22 = x%2==0 || y%2==0 && x+y==23
//    SO HERE WE REACH THE NEXT LEVEL OF NESTING LOGICAL OPERATOR SO WHEN YOU NEST LOGICAL OPERATORS IT WORKS ON ORDER
//    HERE IN THIS EXAMPLE WE HAVE NESTED AN OR AND AN AND OPERATOR TOGETHER SO HERE IT WORKS THIS WAY :-
//    x%2==0 || (y%2==0 && x+y=23) HERE THE RIGHT SIDE OPERATION IS DONE FIRST AND CONSIDERED AS A SEPARATE OPERATION BEFORE THE LEFT ONE IS EXECUTED
    println(is_at_least_one_even_and_is_both_sum_22)





}