// SO TO TACKLE THIS ERROR IN THE PREVIOUS FILE INSTEAD OF .toInt() WE CAN USE .toIntorNull WHICH WILL READ THE INPUT
// AS AN INTEGER IF THATS NOT POSSIBLE SUCH AS WHEN WE INSERT A STRING IT WILL BE CONVERTED TO A NULL VALUE SO ANY VALUE
// THAT CAN'T BE CONVERTED TO AN INTEGER WILL BE CONVERTED TO THE MENTIONED DATA TYPE WILL BE CONVERTED TO A NULL VALUE
// AND NULL IS NOT EQUAL TO 0 ITS THAT NO VALUE OR DATA TYPE IS DECLARED TO THE VARIABLE
fun main() {
    println("Enter a number: ")
    var input_integer_or_null_value = readln().toIntOrNull()

//    var input_integer_or_null_value_even = input_integer_or_null_value % 2 == 0
//    println(input_integer_or_null_value_even)

//    SO NOW FOR THE ABOVE CODE THE IDE THROWS AN ERROR SAYING ITS PROHIBITED BECAUSE THE .toIntOrNull function either returns an
//    INTEGER OR A NULL VALUE SO THERE'S ALWAYS A POSSIBILITY THAT IT COULD RETURN A NULL VALUE SO TO AVOID THIS POSSIBILITY
//    THE COMPILER THROWS AN ERROR SAYING IT'S NULLABLE RECEIVER WHICH CAN CRASH THE PROGRAM HENCE IT'S NOT VALID
//    BUT WHEN INSTEAD OF PERFORMING AN OPERATION RELATED TO THE INTEGER TYPE IF YOU JUST TRY TO PRINT THE VALUE STORED WHEN YOU INPUT
//    A STRING INSTEAD OF AN INTEGER THE PROGRAMS RUNS PERFECTLY FINE AND RETURNS NULL
    println("The input value is $input_integer_or_null_value")

//    NOW A WAY TO JUST THE RUN CODE IS USING THE !! OPERATOR WHICH WILL ALLOW THE COMPILER TO RUN THE CODE EVEN IF THERE IS POSSIBILITY
//    OF A NULL VALUE BUT IT STILL WOULD THROW AN ERROR AND CRASH THE PROGRAM IF ANOTHER DATA TYPE OR NULL VALUE IS PRESENTED
//    SO HERE WE CAN SEE IT GAVE A NULL POINTER EXCEPTION ERROR
//    THE !! OPERATOR TELLS THE COMPILER THAT THERE WILL BE NULL EXCEPTION ERROR SO IN THE END WHEN THE FUNCTION TRIES TO CONVERT A
//    STRING TO A NULL VALUE IT CRASHES 
    val is_even: Boolean=input_integer_or_null_value!!%2==0
    println("The even number is $is_even")

//    THUS THE ABOVE METHOD IS NOT RECOMMENDED AND ALL IT WILL DO IS JUST HELP IN COMPILLING THE CODE
//    SO SINCE IT STILL CRASHES THE PROGRAM WE NEED ANOTHER APPROACH
//    THE BEST APPROACH TO SOLVE THIS PROBLEM IS USING THE ?: OR ?. OPERATOR
//    ?: OPERATOR :-
//    ?: IS USED TO ASSIGN A VALUE TO THE VARIABLE IF THE VARIABLE GETS ASSIGNED A NULL VALUE
    val is_even_or_null_default_to_0= readln().toIntOrNull()?:0
    println("The number is: $is_even_or_null_default_to_0")
}
//